name: Fetch publications from researchmap

on: [workflow_dispatch]

jobs:
  fetch:
    name: fetch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install toml prettyprint requests
    - name: Run script
      run: |
        python tools/import_from_researchmap.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Fetch publications from researchmap
        commit_options: '--no-verify'

        # Optional glob pattern of files which should be added to the commit
        # See the `pathspec`-documentation for git
        # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
        # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
        file_pattern: data/publications/autogen_from_researchmap.toml

        commit_user_name: GitHub Actions Bot
        commit_user_email: github-actions-bot@example.org
        commit_author: GitHub Actions <actions@github.com>

        push_options: '--force'
        skip_dirty_check: true
